from pathlib import Path
import html, json, re, shutil, subprocess, zipfile
from PIL import Image, ImageDraw, ImageFont

ROOT=Path(__file__).resolve().parents[1]
KIT=ROOT.parent/'work/CalibraTrack_OS_Etsy_Seller_Kit_v1.0'
SLUG='calibratrack-os'
ASSET=ROOT/'images/products'/SLUG
ASSET.mkdir(parents=True,exist_ok=True)
titles=['Calibration deadlines','Control center','Due schedule','Certificate evidence','Out-of-tolerance actions','Service and downtime','Vendor performance','Repair or replace','Languages and currencies','Your offline download']
alts=['CalibraTrack OS overview of instrument calibration tracking and upcoming due dates','CalibraTrack OS calibration control center showing health, overdue instruments and evidence gaps','Calibration due schedule for instruments with dates, criticality and service planning','Certificate evidence tracking screen for calibration documents and missing records','Out-of-tolerance action tracking and affected-use review records','Instrument service records, downtime and estimated cost management','Calibration service vendor turnaround and performance overview','Repair-versus-replacement review using instrument service and cost records','CalibraTrack OS language and currency settings for the offline workspace','CalibraTrack OS instant download with the offline HTML application and setup instructions']
font='/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'
bold='/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'
files=sorted((KIT/'02_LISTING_IMAGES').glob('*.jpg'))
for i,src in enumerate(files):
    # Keep the complete supplied visual visible, framed in Nexaly's site colors.
    original=Image.open(src).convert('RGB')
    canvas=Image.new('RGB',(1440,1080),'#f7f3ee'); d=ImageDraw.Draw(canvas)
    d.rounded_rectangle((20,20,1420,1060),radius=34,fill='#fffdfa',outline='#e6ddc9',width=2)
    d.rounded_rectangle((48,48,1392,160),radius=20,fill='#2c2117')
    d.text((78,78),'NEXALY  /  CALIBRATRACK OS',font=ImageFont.truetype(bold,27),fill='#f8eee0')
    d.text((1380,81),f'{i+1:02d} / 10',font=ImageFont.truetype(font,24),fill='#dfb394',anchor='ra')
    visual=original.copy();visual.thumbnail((1310,815),Image.Resampling.LANCZOS)
    canvas.paste(visual,((1440-visual.width)//2,177+(815-visual.height)//2))
    d.text((78,1014),titles[i].upper(),font=ImageFont.truetype(bold,25),fill='#9a4c2d')
    canvas.save(ASSET/f'{i+1:02d}.webp','WEBP',quality=83,method=6)
Image.open(ASSET/'01.webp').save(ROOT/'images/products/calibratrack-os.webp','WEBP',quality=82)
im=Image.open(ASSET/'01.webp');im.thumbnail((480,360));im.save(ROOT/'images/products/thumbs/calibratrack-os.webp','WEBP',quality=78)
for i,src in enumerate(sorted((KIT/'03_LISTING_VIDEOS').glob('*.mp4')),1):shutil.copyfile(src,ASSET/f'video-{i:02d}.mp4')
customer=next((KIT/'01_CUSTOMER_DOWNLOAD').glob('*.zip'))
with zipfile.ZipFile(customer) as z:
    name=next(n for n in z.namelist() if n.endswith('.html'))
    app=z.read(name).decode('utf-8')
demo=ROOT/'demos'/SLUG;demo.mkdir(exist_ok=True)
app=app.replace('<head>','<head><meta name="robots" content="noindex,nofollow,noarchive"><link rel="canonical" href="https://nexalyplanner.com/planners/calibratrack-os/">',1)
guard='''<style>.demo-banner{position:fixed;z-index:999999;bottom:12px;right:12px;background:#2c2117;color:#fff;padding:12px 18px;border-radius:12px;font:600 13px system-ui;box-shadow:0 8px 28px #0005}.demo-banner a{color:#f5ad80;margin-left:12px}</style><div class="demo-banner">CalibraTrack OS · live sample workspace <a href="/planners/calibratrack-os/" target="_top">Product details</a></div>'''
app=app.replace('<body>', '<body>'+guard,1)
# Demo gets a separate storage namespace where applicable. Show a visible sample-data warning on the product page.
(demo/'index.html').write_text(app)
old=(ROOT/'planners/repairbench-os/index.html').read_text()
header=old[old.index('<header class="nav">'):old.index('</header>')+9]
footer=old[old.index('<footer class="site">'):old.index('</footer>')+9]
style=old[old.index('<style>'):old.index('</style>')+8]
style+='''<style>.cal-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(280px,.85fr);gap:34px;max-width:1120px;margin:auto;padding:20px 24px 60px}.cal-hero img{width:100%;border-radius:16px;border:1px solid #e6ddc9}.cal-side{align-self:start;position:sticky;top:90px}.cal-side h1{font-family:Fraunces,serif;color:#2c2117;line-height:1.18}.cal-side p,.cal-copy p,.cal-copy li{color:#5b4a34;line-height:1.7}.cal-tag{font-size:.8rem;font-weight:700;color:#9a4c2d;text-transform:uppercase;letter-spacing:.08em}.cal-cta{display:inline-block;border-radius:10px;background:#c06a3f;color:white!important;text-decoration:none;padding:13px 18px;font-weight:700}.cal-soon{padding:14px;border:1px solid #e6ddc9;border-radius:12px;background:#fff}.cal-copy{background:#fbf6ec;border-top:1px solid #e6ddc9;padding:40px 24px 70px}.cal-inner{max-width:1120px;margin:auto}.cal-copy h2{font-family:Fraunces,serif;color:#2c2117;margin-top:38px}.cal-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.cal-gallery figure{margin:0}.cal-gallery img,.cal-gallery video{width:100%;border-radius:12px;border:1px solid #e6ddc9}.cal-gallery figcaption{font-size:.85rem;color:#5b4a34;margin:6px 0 8px}.cal-demo{width:100%;height:760px;border:1px solid #e6ddc9;border-radius:15px;background:white}.cal-spec{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:0;list-style:none}.cal-spec li{background:white;padding:13px;border-radius:10px;border:1px solid #e6ddc9}@media(max-width:750px){.cal-grid{grid-template-columns:1fr}.cal-side{position:static}.cal-gallery,.cal-spec{grid-template-columns:1fr}.cal-demo{height:680px}}</style>'''
head='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calibration Tracking Software | CalibraTrack OS | Nexaly Planner</title><meta name="description" content="Track instrument calibration due dates, certificates, out-of-tolerance actions, service costs and vendors with CalibraTrack OS. Private offline software, no subscription."><meta name="nexaly:checkout" content="pending"><meta name="product:price:amount" content="11.99"><link rel="canonical" href="https://nexalyplanner.com/planners/calibratrack-os/"><meta property="og:type" content="product"><meta property="og:title" content="CalibraTrack OS — Offline Calibration Tracking Software"><meta property="og:description" content="Manage calibration schedules, certificate references, service work and instrument history in one offline workspace."><meta property="og:image" content="https://nexalyplanner.com/images/products/calibratrack-os.webp"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/assets/css/style.css?v=3"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fraunces:wght@400;600;700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">'''
schema={'@context':'https://schema.org','@type':'Product','name':'CalibraTrack OS','description':'Offline calibration and instrument service management software for schedules, certificate references, out-of-tolerance actions and service history.','brand':{'@type':'Brand','name':'Nexaly Planner'},'image':'https://nexalyplanner.com/images/products/calibratrack-os.webp'}
head+='<script type="application/ld+json">'+json.dumps(schema)+'</script>'+style+'</head><body>'
imgs=''.join(f'<figure><img src="/images/products/{SLUG}/{i+1:02d}.webp" alt="{html.escape(alts[i])}" loading="lazy" width="1440" height="1080"><figcaption>{html.escape(titles[i])}</figcaption></figure>' for i in range(10))
vids=''.join(f'<figure><video controls preload="none" playsinline poster="/images/products/{SLUG}/{i:02d}.webp"><source src="/images/products/{SLUG}/video-{i:02d}.mp4" type="video/mp4"></video><figcaption>{"Overview of calibration tracking" if i==1 else "CalibraTrack features tour"}</figcaption></figure>' for i in (1,2))
body=f'''<div class="pd-crumb"><a href="/">Home</a> / <a href="/planners/">Products</a> / CalibraTrack OS</div><main><section class="cal-grid"><div class="cal-hero"><img src="/images/products/{SLUG}/01.webp" alt="{alts[0]}" width="1440" height="1080" fetchpriority="high"></div><div class="cal-side"><span class="cal-tag">Business Operating Systems · Offline download</span><h1>Calibration Tracking Software for Instruments and Service Records</h1><p>CalibraTrack OS keeps your instrument register, calibration dates, certificate references, service work and out-of-tolerance follow-up in one private browser workspace.</p><ul class="pd-hl"><li>Offline</li><li>One-time download</li><li>No account</li><li>7 languages</li></ul><a class="cal-cta" href="#live-demo">Explore the live demo</a><p class="cal-soon"><strong>Checkout coming soon.</strong> This product is being listed now; payment and delivery will be enabled with the new collection.</p></div></section><section class="cal-copy"><div class="cal-inner"><h2>See the complete workspace</h2><p>Browse all ten views, then open the live sample workspace to explore the actual software.</p><div class="cal-gallery">{imgs}</div><h2>Watch the overview and feature tour</h2><div class="cal-gallery">{vids}</div><h2 id="live-demo">Try CalibraTrack OS</h2><p>Interactive sample data is for evaluation. Use fictional records only; do not enter private business or customer information. Browser data is local to your device.</p><iframe class="cal-demo" title="CalibraTrack OS interactive sample workspace" src="/demos/{SLUG}/" loading="lazy" sandbox="allow-scripts allow-same-origin allow-forms"></iframe><h2>What's included</h2><ul class="cal-spec"><li>Instrument register and calibration schedule</li><li>Calibration events and certificate references</li><li>Out-of-tolerance reviews and corrective actions</li><li>Service work orders, downtime and estimated costs</li><li>Vendor turnaround and spending reports</li><li>JSON backup and restore; CSV instrument export</li></ul><h2>Download and compatibility</h2><p>The customer download contains a self-contained HTML app and a Read Me First guide. Extract the ZIP and open the HTML file in a modern desktop browser. Records stay in that browser; save JSON backups regularly, especially before clearing browser data or moving devices. Choosing a currency changes the display format and does not convert exchange rates.</p><h2>Important limits</h2><p>CalibraTrack OS is an internal recordkeeping and management aid. It does not certify ISO or regulatory compliance, approve calibration results, or authorize instrument use or return to service. Qualified personnel remain responsible for those decisions.</p><p>Explore related tools: <a href="/planners/vendorpulse-os/">supplier performance management with VendorPulse OS</a> and <a href="/planners/inventory-procurement-planner/">inventory and procurement planning</a>.</p></div></section></main>'''
page=ROOT/'planners'/SLUG;page.mkdir(exist_ok=True)
(page/'index.html').write_text(head+header+body+footer+'<script src="/assets/js/main.js"></script></body></html>')
js=ROOT/'assets/js/main.js';s=js.read_text();needle='var products = [\n';entry={'title':'CalibraTrack OS — Calibration & Instrument Service Manager','cat':'Business Operating Systems','desc':'Track calibration due dates, certificate references, out-of-tolerance actions, service work, downtime and vendor performance in a private offline browser app.','price':11.99,'img':'/images/products/calibratrack-os.webp','thumb':'/images/products/thumbs/calibratrack-os.webp','video':'','buyUrl':'','url':'/planners/calibratrack-os/','m1':'#EFE4D9','m2':'#E8D1BE'}
assert needle in s
js.write_text(s.replace(needle,needle+'  '+json.dumps(entry,ensure_ascii=False)+',\n',1))
print('Created product page, demo, catalog entry, ten images and two videos')
