"""One-off editorial source for the 28 September 2026 journal batch."""
from pathlib import Path
import html, json, re
from deep_plans import DEEP_PLANS, IMPLEMENTATION_NOTES

ROOT=Path(__file__).resolve().parents[1]
DATE='2026-09-28'
SITE='https://nexalyplanner.com'
template=(ROOT/'journal/business-planner-weekly-review/index.html').read_text()
styles=template[template.index('<style>'):template.index('</style>')+8]
nav=template[template.index('<header class="nav">'):template.index('</header>')+9]
footer=template[template.index('<footer class="site">'):]

articles=[
dict(slug='retail-store-business-plan-example',title='Retail Store Business Plan Example: A Boutique’s First 90 Days',tag='Business Planning',accent='#126b65',subtitle='A filled-in plan for assortment, cash, sales and a decision date.',metric=['$4,800','120 units','$2,160'],labels=['Opening cash','Initial stock','Month 1 sales'],
body='''<p>A retail store business plan should connect an offer and a customer to the stock, cash and work needed to make the store run. This example follows a fictional online clothing boutique, Willow Thread, through its first 90 days. All amounts are illustrative USD assumptions, not industry averages.</p>
<div class="note"><strong>Quick answer:</strong> define the customer and product range, estimate sales by units and price, calculate stock cost and other cash outflows, then set a date to compare the plan with actual results.</div>
<h2>Start with a narrow offer and a testable customer</h2>
<p>Willow Thread sells 12 everyday clothing styles to local buyers through an online storefront and weekend pickup. Its first hypothesis is that buyers will choose coordinated outfits at a $36 average item price. This is a planning assumption, not a validated market finding. The owner will record which styles sell, returns and requests for unavailable sizes before increasing the range.</p>
<p>The <a href="https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan">SBA business-plan guide</a> recommends describing the market, product, sales approach and financial projections. A compact operating version can fit on a page, provided the owner keeps the assumptions and supporting records.</p>
<h2>Build the opening-stock and monthly-sales math</h2>
<div class="table-wrap"><table><caption>Illustrative boutique opening plan</caption><thead><tr><th>Item</th><th>Calculation</th><th>Amount</th></tr></thead><tbody><tr><td>Opening inventory</td><td>120 units × $18 landed cost</td><td>$2,160 cash out</td></tr><tr><td>Month 1 sales</td><td>60 units × $36 average selling price</td><td>$2,160 revenue</td></tr><tr><td>Cost of sold units</td><td>60 × $18</td><td>$1,080</td></tr><tr><td>Gross margin before other costs</td><td>$2,160 − $1,080</td><td>$1,080, or 50%</td></tr><tr><td>Other monthly costs</td><td>Site $45 + packaging $90 + promotion $250 + pickup $120</td><td>$505</td></tr><tr><td>Illustrative operating contribution</td><td>$1,080 − $505</td><td>$575 before fees, returns, tax and owner pay</td></tr></tbody></table></div>
<p>The $2,160 inventory purchase happens before all 120 units are sold. Gross margin is therefore not the same as bank balance. If opening cash is $4,800, the stock and $505 of monthly operating costs leave $2,135 before customer receipts and other bills. Track inventory and cash separately.</p>
<h2>Translate the plan into a 90-day decision rule</h2>
<p>In weeks 1–4, list all 12 styles, photograph the products and log size-level sales. In weeks 5–8, compare sell-through by style, not just total revenue. In weeks 9–12, reorder only lines with evidence of demand and workable supplier lead times. If 60 of 120 units sell in month 1, the overall sell-through is 50%; it does not mean every size is equally healthy.</p>
<p>For stock-level records and purchase decisions, use the <a href="/planners/boutique-business-planner/">Boutique Business Planner</a> and the <a href="/journal/reorder-point-small-business/">reorder-point method</a>. Record actual unit cost, returns and payment fees before deciding what to buy again.</p>
<h2>What belongs in the full plan?</h2>
<p>Keep a short summary, target customer, product and supplier assumptions, sales channels, fulfillment steps, monthly forecast, cash needs and risks. If seeking financing, expand the financial statements and evidence to the lender’s requirements. On day 90, replace the hypothetical $36 price, 60-unit sales and $18 cost with actuals; keep both versions so forecast errors are visible.</p>''',
related='/planners/boutique-business-planner/'),
dict(slug='freelance-business-plan-example',title='Freelance Business Plan: Capacity, Pricing and a 90-Day Example',tag='Business Planning',accent='#7c4d74',subtitle='Turn available hours into a realistic revenue and delivery plan.',metric=['80 h','$75/h','$3,750'],labels=['Monthly capacity','Project rate','Target receipts'],
body='''<p>A freelance business plan works best when it starts with billable capacity rather than a revenue wish. This example uses a fictional independent designer who has 80 working hours available each month. The figures are illustrative USD assumptions.</p>
<div class="note"><strong>Quick answer:</strong> specify the client problem, offer, price, capacity, acquisition channel, payment terms and a cash reserve. Review projects and unpaid invoices every week.</div>
<h2>Define the offer and the limits</h2>
<p>The designer offers a fixed-scope landing-page design package for $1,250, estimated at 16 delivery hours plus 4 hours of discovery and revisions. Three packages per month would produce $3,750 invoiced revenue and use 60 hours. The remaining 20 hours cover proposals, admin and unexpected revisions. The effective planned rate is $3,750 ÷ 60 client hours = $62.50; it is below a quoted $75 hourly alternative because the package includes non-design work.</p>
<p>Do not promise four packages simply because 80 ÷ 20 = 4. That would leave no time for selling, bookkeeping or delays. The <a href="https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan">SBA’s business-plan outline</a> provides a larger framework; a solo operator still needs an explicit capacity constraint.</p>
<h2>Put acquisition and cash timing in the same plan</h2>
<div class="table-wrap"><table><caption>Illustrative freelance monthly model</caption><thead><tr><th>Measure</th><th>Assumption</th><th>Result</th></tr></thead><tbody><tr><td>Qualified inquiries</td><td>12 per month</td><td>12</td></tr><tr><td>Proposal rate</td><td>8 of 12 inquiries</td><td>8 proposals</td></tr><tr><td>Win rate</td><td>3 of 8 proposals</td><td>37.5%</td></tr><tr><td>Booked work</td><td>3 × $1,250</td><td>$3,750 invoiced</td></tr><tr><td>Direct software and contractor costs</td><td>$180 + $420</td><td>$600</td></tr><tr><td>Amount before taxes, overhead and owner pay</td><td>$3,750 − $600</td><td>$3,150</td></tr></tbody></table></div>
<p>If one client pays a month late, $1,250 of invoices may not be available to pay current bills. Track booked work, invoices sent and cash collected as separate numbers. The <a href="https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping">IRS recordkeeping guidance</a> explains why the underlying income and expense evidence needs its own system.</p>
<h2>Run a 90-day experiment</h2>
<p>Month 1: interview five prospective clients, price the package and complete one pilot with a written scope. Month 2: publish two concrete case studies only with client permission and track 12 qualified inquiries. Month 3: compare actual delivery hours with the 20-hour estimate. If an average package takes 26 hours, three projects use 78 hours and the current plan is overloaded. Raise the price, narrow scope or reduce the booking target.</p>
<p>The <a href="/planners/owneros-core/">OwnerOS Core</a> can organize priorities and follow-ups; the <a href="/planners/agency-client-profitability-capacity-os/">agency capacity planner</a> is relevant when several clients and collaborators need a shared delivery view. Neither replaces a contract or accounting records.</p>''',
related='/planners/owneros-core/'),
dict(slug='equipment-rental-business-plan-example',title='Equipment Rental Business Plan Example: Utilization and Cash',tag='Business Planning',accent='#9a683b',subtitle='Price a small event-equipment fleet with utilization and turn costs.',metric=['20','$90','$720'],labels=['Available dates','Rental price','Gross contribution'],
body='''<p>An event-equipment rental business plan must account for idle days, maintenance and turnaround work. This example is for a fictional company renting portable event lighting, not residential property. All figures are illustrative USD assumptions.</p>
<div class="note"><strong>Quick answer:</strong> describe the inventory, usable booking dates, rental rate, expected utilization, cleaning and delivery cost, deposits, damage process and cash needed to buy replacements.</div>
<h2>Calculate availability before revenue</h2>
<p>Suppose one lighting kit can be offered on 20 dates each month at $90 per booking. The owner expects 10 booked dates, so utilization is 10 ÷ 20 = 50%. Gross rental receipts are 10 × $90 = $900. If cleaning, consumables and delivery average $18 per booking, variable costs are $180 and contribution is $720 before storage, insurance, repairs and equipment purchase.</p>
<div class="table-wrap"><table><caption>Illustrative one-kit utilization sensitivity</caption><thead><tr><th>Bookings</th><th>Utilization</th><th>Receipts</th><th>After $18 per booking</th></tr></thead><tbody><tr><td>6</td><td>30%</td><td>$540</td><td>$432</td></tr><tr><td>10</td><td>50%</td><td>$900</td><td>$720</td></tr><tr><td>14</td><td>70%</td><td>$1,260</td><td>$1,008</td></tr></tbody></table></div>
<p>If fixed monthly costs attributable to the kit are $400, contribution after those costs at 10 bookings is $320. A $2,400 kit would take at least 7.5 such months to recover its initial cost in this simplified model ($2,400 ÷ $320), assuming the same demand and no other expenses. That is not a promise of payback; seasonality and repairs can change it.</p>
<h2>Map the work from quote to return</h2>
<p>Document each kit’s serial number and condition. Reserve the date only when the agreed booking condition is met, then confirm pickup or delivery, return time, deposit terms and damage process in writing. Hold time for testing and cleaning between bookings. A calendar that shows the kit as available on a return day can create a double-booking if inspection takes until the next morning.</p>
<p>The <a href="/planners/rentflow-os/">RentFlow planner</a> is aimed at equipment and event rental workflows. Use it to keep bookings, handoffs and utilization visible; retain actual contracts and financial records in the appropriate systems. The <a href="https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan">SBA plan guide</a> covers the broader market and funding sections if this plan is being presented externally.</p>
<h2>Choose a measurable 90-day test</h2>
<p>Start with one kit and a 10-booking monthly target. Each Friday, record available dates, bookings, declined requests, late returns, repair days and cash receipts. If 15 requests arrive but only 8 bookings close, review quote speed and price before purchasing a second kit. If 10 bookings close but three require costly repairs, revise inspection and deposit rules before expanding.</p>''',
related='/planners/rentflow-os/'),
dict(slug='saas-business-plan-template-example',title='SaaS Business Plan Template: Runway and Subscription Math',tag='Business Planning',accent='#455f93',subtitle='A compact subscription plan with churn, margin and runway assumptions.',metric=['100','$30','12 mo'],labels=['Starting users','Monthly price','Runway target'],
body='''<p>A SaaS business plan needs more than a subscription revenue target. It needs a clear customer problem, acquisition assumptions, service costs, churn and enough cash to continue while the model is tested. The figures below are fictional USD examples, not NexalyPlanner product metrics.</p>
<div class="note"><strong>Quick answer:</strong> write the customer and offer first, then model subscribers gained and lost, revenue collected, variable service costs and monthly net cash burn. Update assumptions with actual cohorts.</div>
<h2>Separate subscriptions, revenue and cash</h2>
<p>Assume a small software service begins a month with 100 paying accounts at $30 per month. It adds 20 accounts and loses five. Ending accounts are 115. If new accounts start halfway through the month and cancellations stop at month-end, a simplified recognized monthly revenue estimate is 100 × $30 + 20 × $15 = $3,300. Actual billing and revenue recognition depend on contract and payment terms. Cash receipts may differ.</p>
<div class="table-wrap"><table><caption>Illustrative subscription operating model</caption><thead><tr><th>Line</th><th>Assumption</th><th>Monthly amount</th></tr></thead><tbody><tr><td>Starting recurring billings</td><td>100 × $30</td><td>$3,000</td></tr><tr><td>Service cost</td><td>115 ending accounts × $4</td><td>$460 estimate</td></tr><tr><td>Marketing spend</td><td>20 acquired accounts × $40 acquisition spend</td><td>$800</td></tr><tr><td>Other cash operating costs</td><td>Hosting, support and founder draw</td><td>$3,000 assumed</td></tr><tr><td>Illustrative cash movement</td><td>$3,300 receipts − $460 − $800 − $3,000</td><td>−$960</td></tr></tbody></table></div>
<p>This model deliberately treats the $3,300 as cash received for the illustration. If annual plans, refunds or unpaid invoices exist, replace it with actual receipts. Five cancellations from 100 starting accounts imply 5% monthly logo churn; the number is an assumption to test, not a normal benchmark.</p>
<h2>Check runway without pretending the burn is constant</h2>
<p>With $12,000 unrestricted cash and $960 of monthly net outflow, simple runway is $12,000 ÷ $960 = 12.5 months. It is a snapshot, not a forecast: hiring, taxes, renewals or seasonal sales will change burn. Make a month-by-month cash schedule and a downside case. If receipts fall to $2,500 while outflows stay $4,260, burn becomes $1,760 and simple runway falls to about 6.8 months.</p>
<p>The <a href="/planners/business-runway-burn-rate-os/">Business Runway &amp; Burn Rate planner</a> helps keep cash assumptions and scenarios visible. For a wider planning outline, consult the <a href="https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan">SBA business plan guidance</a>. Financing or accounting decisions require the relevant professional records and advice.</p>
<h2>What to review every month</h2>
<p>Track beginning customers, new customers, cancellations, ending customers, receipts, service cost, acquisition spend and cash balance. Name the owner of each metric and the source system. Revisit pricing only after examining customer retention and unit economics; increasing signups at a loss can shorten runway.</p>''',
related='/planners/business-runway-burn-rate-os/'),
dict(slug='one-page-marketing-plan-example',title='One-Page Marketing Plan Template With a Worked $600 Budget',tag='Marketing Planning',accent='#aa5c50',subtitle='An audience, offer, channel and measurement plan on one page.',metric=['$600','80','8'],labels=['Test budget','Qualified visits','Orders'],
body='''<p>A one-page marketing plan makes a few choices visible: who you serve, what you offer, how people will find it and how you will decide whether to continue. This worked example uses a fictional boutique launching a capsule collection. All numbers are assumptions in USD.</p>
<div class="note"><strong>Quick answer:</strong> write one audience, one offer, two channels, a dated budget and a measure that links activity to actual orders. Keep the full evidence behind the page.</div>
<h2>The filled-in plan</h2>
<div class="table-wrap"><table><caption>Illustrative one-page marketing plan for a 30-day launch</caption><thead><tr><th>Field</th><th>Filled example</th></tr></thead><tbody><tr><td>Audience</td><td>Local buyers seeking mix-and-match workwear under $75 per item</td></tr><tr><td>Offer</td><td>Four-piece capsule with a clear size guide and pickup option</td></tr><tr><td>Goal</td><td>Eight paid orders during a 30-day test</td></tr><tr><td>Channels</td><td>Two weekly email sends to existing subscribers; three short product demonstrations weekly</td></tr><tr><td>Budget</td><td>$360 creative production + $240 paid distribution = $600 ceiling</td></tr><tr><td>Measure</td><td>Qualified visits, add-to-cart events, orders, refunds and spend by channel</td></tr><tr><td>Decision date</td><td>Day 31: compare orders and contribution after product and marketing costs</td></tr></tbody></table></div>
<p>If 80 qualified visits produce eight paid orders, observed visit-to-order conversion is 10% for this small test. The $600 spend divided by eight orders is $75 marketing cost per order before any return buyers. If each order contributes $38 after product and fulfillment cost, eight orders contribute $304, which does not cover $600 of marketing. The owner should investigate attribution and customer value before repeating the same spend; the test has not demonstrated immediate profitability.</p>
<h2>Strategy, plan and campaign play different roles</h2>
<p>The strategy is the choice to serve local workwear buyers with a practical capsule. The plan assigns channels, budget, dates and metrics. The campaign is the 30-day launch activity. The <a href="https://www.score.org/tools/quick-start-marketing-plan/">SCORE Quick Start Marketing Plan</a> provides a fuller external worksheet if you need additional fields.</p>
<h2>Keep the calendar usable</h2>
<p>Block production, approval and publishing dates before adding more content ideas. For example, Monday photos, Tuesday email draft, Wednesday review and Thursday send. Record the same attribution rule on every week; do not credit all eight orders to both channels. The <a href="/planners/content-marketing-planner/">Content Marketing Planner</a> can organize the schedule, while the <a href="/journal/content-calendar-clothing-brand/">clothing-brand content calendar guide</a> gives a more detailed editorial workflow.</p>
<p>After day 31, note what the page cannot tell you: customer interviews, repeat orders and whether the visit counts were comparable. Update the offer or channel based on those observations rather than changing every variable at once.</p>''',
related='/planners/content-marketing-planner/'),
dict(slug='cash-flow-forecast-template-example',title='Cash Flow Forecast Template: A 13-Week Worked Example',tag='Financial Planning',accent='#277789',subtitle='Forecast receipts and payments week by week without mixing in profit.',metric=['$5,000','$1,300','$4,200'],labels=['Opening cash','Week 1 net','Week 4 closing'],
body='''<p>A cash flow forecast lists when money is expected to enter and leave the business. It answers a different question from a profit statement: can the business meet payments on the dates they fall due? This 13-week structure works in a spreadsheet or a dedicated planner. The figures are illustrative USD assumptions.</p>
<div class="note"><strong>Quick answer:</strong> start with bank cash, add expected customer receipts by payment date, subtract payroll, suppliers, tax set-asides and other payments by due date, then carry closing cash into the next week.</div>
<h2>Use one row for each expected cash movement</h2>
<p>For a fictional small shop, opening cash is $5,000. In week 1 it expects $2,800 from customers and pays $900 to suppliers, $400 for rent and $200 for other bills. Closing cash is $5,000 + $2,800 − $1,500 = $6,300. This $1,300 net inflow says nothing by itself about profit: the stock may have been bought earlier and the receipts may relate to prior sales.</p>
<div class="table-wrap"><table><caption>Illustrative four-week excerpt from a 13-week cash forecast</caption><thead><tr><th>Week</th><th>Opening</th><th>Receipts</th><th>Payments</th><th>Closing</th></tr></thead><tbody><tr><td>1</td><td>$5,000</td><td>$2,800</td><td>$1,500</td><td>$6,300</td></tr><tr><td>2</td><td>$6,300</td><td>$1,700</td><td>$3,200</td><td>$4,800</td></tr><tr><td>3</td><td>$4,800</td><td>$2,100</td><td>$2,700</td><td>$4,200</td></tr><tr><td>4</td><td>$4,200</td><td>$2,000</td><td>$2,000</td><td>$4,200</td></tr></tbody></table></div>
<p>In a spreadsheet, closing cash for each column is <code>opening + receipts − payments</code>, and the next column’s opening equals the preceding closing. Extend the same five lines through week 13. Label uncertain receipts separately; do not count an unsigned quote as money in the bank.</p>
<h2>Stress-test the lowest week</h2>
<p>If $1,200 of week 2 receipts moves to week 5, week 2 closing becomes $3,600 rather than $4,800, and week 3 closing becomes $3,000 rather than $4,200. The owner can plan supplier timing or an authorized funding source before the shortfall becomes urgent. Keep a minimum cash threshold that reflects actual obligations; do not treat a generic percentage as a universal rule.</p>
<p>Use the <a href="/planners/cashflow-13-os/">CashFlow 13 planner</a> for a rolling 13-week view. The <a href="https://www.sba.gov/blog/2019/2019-07/5-classic-fails-budgets-forecasts/">SBA discussion of budgets and forecasts</a> recommends matching categories to actual accounting reports. Confirm receipts and payments against bank and bookkeeping records; the planner is a decision aid, not the books.</p>
<h2>Update on the same weekday</h2>
<p>Replace last week’s forecast with actual cash movements, explain large differences, and add a new thirteenth week. Note the date, source and owner of each assumption. If the gap is a late invoice, assign a follow-up; if it is a recurring cost, revise future weeks rather than hiding it in a one-time adjustment.</p>''',
related='/planners/cashflow-13-os/'),
dict(slug='weekly-digital-planner-small-business',title='Weekly Digital Planner for a Small Business: A Filled Example',tag='Digital Planners',accent='#4d7088',subtitle='Turn a weekly goal into time blocks, handoffs and a Friday review.',metric=['3','6 h','Friday'],labels=['Weekly priorities','Protected work','Review date'],
body='''<p>A weekly digital planner is useful when it helps you decide which work belongs on the calendar and what can wait. This example follows a fictional solo shop owner balancing customer orders, stock and marketing. It is an illustrative workflow, not a claim that one layout fits every business.</p>
<div class="note"><strong>Quick answer:</strong> choose three outcomes for the week, reserve time for delivery and customer promises, assign each task a date and review what actually happened on Friday.</div>
<h2>Plan outcomes before filling hours</h2>
<p>The owner’s three outcomes are: ship 20 open orders by Thursday, confirm a replacement supplier by Wednesday and publish next week’s launch email by Friday. The calendar already has four hours of customer support and two hours of bookkeeping. She protects two 90-minute packing blocks, a one-hour supplier comparison and a two-hour email block: six hours of focused work in total.</p>
<div class="table-wrap"><table><caption>Illustrative weekly digital planner entries</caption><thead><tr><th>Day</th><th>Block</th><th>Output and evidence</th></tr></thead><tbody><tr><td>Monday</td><td>09:00–10:30 packing</td><td>10 orders marked shipped with tracking</td></tr><tr><td>Tuesday</td><td>11:00–12:00 suppliers</td><td>Three quotes compared on landed cost and lead time</td></tr><tr><td>Wednesday</td><td>09:00–10:30 packing</td><td>Remaining 10 orders shipped or exceptions noted</td></tr><tr><td>Thursday</td><td>14:00–16:00 email</td><td>Draft, links and offer checked</td></tr><tr><td>Friday</td><td>15:00–15:20 review</td><td>Three outcomes marked done, moved or blocked</td></tr></tbody></table></div>
<p>There is a scheduling mistake in the first draft: Wednesday’s packing block could finish the orders, but the commitment is Thursday. Add Thursday as an exception buffer, not as another promised 10-order batch. The plan should show deadlines and spare capacity honestly.</p>
<h2>Use links and status without duplicating every record</h2>
<p>Keep the order numbers in the order system, supplier quotes in the procurement record and payment data in the accounting system. The weekly planner can point to those sources and record the next action. If a supplier quote is $15 per unit plus $80 shipping for 40 units, landed cost is $17 per unit; that calculation belongs beside the comparison, not in a vague “follow up” task.</p>
<p>The <a href="/planners/small-business-planner-2026-2028/">Small Business Planner</a> offers a planning home for dates and priorities. For the operational review, see the <a href="/journal/business-planner-weekly-review/">weekly business review guide</a>; for working without a live connection, see the <a href="/journal/offline-digital-planners-guide/">offline planner guide</a>. Check the product page for exact format and device compatibility before buying.</p>
<h2>Review the plan rather than copying it forward</h2>
<p>At Friday’s review, count completed outcomes and record the cause of misses. If 16 rather than 20 orders shipped because four addresses were incomplete, the next action is to collect those addresses, not to schedule four unexplained tasks next week. Adjust future packing estimates with actual time per order.</p>''',
related='/planners/small-business-planner-2026-2028/'),
dict(slug='small-business-budget-example',title='Small Business Budget Example: Plan Costs, Then Compare Actuals',tag='Financial Planning',accent='#6c7650',subtitle='A practical monthly budget with a variance and cash check.',metric=['$8,000','$5,600','$800'],labels=['Sales plan','Cost plan','Cash gap test'],
body='''<p>A small business budget turns a sales assumption into spending limits and a comparison with actual results. This example is a fictional service-and-product shop with a monthly plan in USD. It is a management illustration; accounting statements and tax records use their own rules.</p>
<div class="note"><strong>Quick answer:</strong> plan revenue, variable cost, fixed cost and an owner-pay assumption; compare each with actuals on the same basis; then check the separate timing of cash receipts and bills.</div>
<h2>Build a simple monthly budget</h2>
<p>Assume 100 orders at an $80 average selling price, for $8,000 planned sales. Variable product, shipping and payment costs average $28 per order, or $2,800. Fixed costs are $1,200 rent, $600 software and utilities, $600 marketing and $400 insurance, totaling $2,800. The remaining $2,400 is before owner pay, tax and financing costs. If the owner plans a $1,600 draw, only $800 remains as an illustrative cushion. A draw is not necessarily an expense in the formal profit statement.</p>
<div class="table-wrap"><table><caption>Illustrative budget versus actual, one month</caption><thead><tr><th>Line</th><th>Budget</th><th>Actual</th><th>Difference</th></tr></thead><tbody><tr><td>Sales</td><td>$8,000</td><td>$7,200</td><td>−$800</td></tr><tr><td>Variable costs</td><td>$2,800</td><td>$2,700</td><td>−$100</td></tr><tr><td>Fixed costs</td><td>$2,800</td><td>$2,900</td><td>+$100</td></tr><tr><td>Before owner pay, tax and financing</td><td>$2,400</td><td>$1,600</td><td>−$800</td></tr></tbody></table></div>
<p>The sales shortfall does not by itself explain the whole result. If 90 actual orders generated $7,200, average price stayed $80. Variable cost per order increased to $30 ($2,700 ÷ 90), while fixed costs rose $100. That gives two specific questions: why did order count fall by 10, and why did unit cost rise by $2?</p>
<h2>Check cash separately</h2>
<p>Suppose $800 of those sales will be collected next month while all $5,600 of actual costs are paid now. Cash from these activities is $6,400 − $5,600 = $800 before the $1,600 owner draw, creating an $800 cash gap. The $1,600 operating result is not available cash. Use a dated forecast to see whether opening cash can cover the gap.</p>
<p>The <a href="/planners/business-runway-burn-rate-os/">Business Runway &amp; Burn Rate planner</a> can help frame cash scenarios, and the <a href="/journal/cash-flow-forecast-template-example/">13-week cash forecast example</a> shows payment timing in detail. The <a href="https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping">IRS recordkeeping guidance</a> covers the need to retain supporting income and expense evidence.</p>
<h2>Make the next month’s decision</h2>
<p>Do not simply raise the next sales target to erase the variance. Check traffic, inquiries, conversion, refunds and stock availability; confirm whether the $2 unit-cost change is a one-off fee or a new supplier price. Then revise the unit assumptions and spending ceiling, and date the revised budget so the original forecast remains auditable.</p>''',
related='/planners/business-runway-burn-rate-os/')
]

extras={
'retail-store-business-plan-example':'''<h2>Write down the assumptions that could break the plan</h2><p>The 50% gross margin assumes that all 60 sold units fetch $36 and cost $18 landed. Suppose six units are returned and refunded while the cost of handling each return is $4. If the returned units cannot be resold immediately, net retained sales fall to 54 × $36 = $1,944, and handling adds $24. Review return rates by style before treating the original $575 contribution as earned. A plan that shows returns only as a footnote will overstate usable cash.</p><p>Make one purchasing rule explicit: order a second batch only when a style’s size-level sell-through, actual margin and supplier lead time support it. If a popular size sells out while unpopular sizes remain, the overall 50% sell-through hides the problem. Compare quoted shipping, minimum order quantities and payment terms, then record why the selected supplier won. The <a href="/journal/supplier-quote-comparison/">supplier comparison guide</a> shows a consistent landed-cost method.</p><h2>Copyable plan fields</h2><p>Record the target buyer and need; the 12-style range and prices; 120-unit opening stock by size; the $4,800 opening cash; the sales and returns assumptions; who packs and fulfills orders; the reorder trigger; and the day-30, day-60 and day-90 review dates. Each field needs an owner and an evidence source. That makes the plan usable when results differ from the forecast.</p>''',
'freelance-business-plan-example':'''<h2>Test the price against hours actually delivered</h2><p>The $1,250 package is only attractive if scope stays controlled. Suppose one project takes 16 planned design hours, four planned discovery and revision hours, plus six unexpected revision hours. Its 26 hours produce $48.08 per hour before direct costs ($1,250 ÷ 26). At that pace three projects consume 78 hours, leaving just two hours for proposals and admin. A fourth client would create a delivery promise the calendar cannot support. Write the included revision rounds and the change-request process into the offer.</p><p>Cash timing needs a separate rule. If clients pay 50% at booking and 50% on delivery, three booked packages may bring in $1,875 initially, not $3,750. The plan should list each milestone, expected payment date and follow-up owner. If one project slips, the second payment slips too. Do not spend against an invoice that has not been collected.</p><h2>What to review on Friday</h2><p>Compare qualified inquiries, proposals, wins, hours estimated versus actual, open client commitments and unpaid invoices. If the win rate drops, inspect the client fit and proposal terms before simply increasing outreach volume. If delivery hours rise, reduce bookings or change the package scope. Record client permission before turning work into a case study, and keep confidential project material outside public marketing.</p>''',
'equipment-rental-business-plan-example':'''<h2>Add the expenses hidden by the booking calendar</h2><p>The $18 variable amount includes routine turnaround, but it does not cover a surprise lamp replacement, damaged cable, insurance premium or storage. Suppose the kit needs a $360 repair in month 2. At 10 bookings, that month’s $320 after fixed costs becomes a $40 loss. A replacement reserve is an operational choice based on equipment life and service history; it should be shown as a cash allocation rather than quietly subtracted from every booking without explanation.</p><p>Delivery distance matters too. At a $90 price, a long-distance booking with $35 delivery and $18 cleaning leaves $37 before fixed costs, less than a local pickup’s $72 after the original $18 variable cost. The quote should state delivery boundaries, labor, setup and return conditions. Compare contribution by booking type, not just the number of calendar reservations.</p><h2>Document a cancellation scenario</h2><p>Imagine a 14-booking forecast but four events cancel, leaving 10 completed rentals. The revenue difference is $360; avoided $18 variable costs on four bookings are $72. Contribution is $288 lower than planned. A deposit policy and cancellation terms may reduce exposure, but their enforceability depends on the actual contract and local law. Record the accepted terms before the event. Review utilization against available dates, not total calendar days, so maintenance closures are visible.</p>''',
'saas-business-plan-template-example':'''<h2>Check acquisition payback with the right denominator</h2><p>The example spends $800 to acquire 20 accounts, or $40 per new account. If the service costs $4 per account per month, the simplified contribution at a $30 price is $26 per month before support, refunds, payment fees and overhead. A $40 acquisition cost divided by $26 suggests roughly 1.54 paid months to recover that particular spend, but only if accounts remain and collectable receipts arrive as modeled. It is not a full customer lifetime value calculation.</p><p>Five cancellations are also a warning about the denominator. Five of 100 starting customers is 5% logo churn for that month. If the lost customers paid different prices, revenue churn would differ. Track both when plans vary. One month’s churn is too little evidence to extrapolate years of retention. Keep the cohort and cancellation reason rather than replacing observed data with an industry benchmark.</p><h2>Use the plan as a decision schedule</h2><p>By the first review, validate whether 20 new accounts came from the $800 channel spend and whether onboarding succeeded. By month 2, compare actual service cost per active account and unpaid invoices. By month 3, rerun the downside runway scenario with current cash and signed commitments. If acquisition is efficient but support costs are rising, improving onboarding may be a better test than buying more traffic. Document who owns each experiment and when it will stop.</p>''',
'one-page-marketing-plan-example':'''<h2>Measure the funnel without claiming false precision</h2><p>The 80 qualified visits and eight orders are small counts. If two buyers cancel, net orders are six, net observed conversion is 7.5%, and the $600 spend becomes $100 per retained order. This sensitivity is why a single test should guide a follow-up question, not establish a permanent conversion rate. Record the attribution window, whether an order was new or returning, and which refunds were included.</p><p>A more useful next test might keep the $75 item and target audience constant while changing one message. If the email emphasizes fit and sizing rather than a discount, compare add-to-cart and refund behavior as well as clicks. Do not change channel, audience, price and creative together, because the source of any difference will be unclear.</p><h2>How to maintain the one-page document</h2><p>Keep the current version at the top, with a dated line for the goal, budget, owner and review date. Store the campaign calendar and detailed asset links elsewhere. Each week, enter spend, qualified visits, orders and refunds using the same definitions. At the review, write one sentence: continue, revise or stop, with the number that supports the decision. If $304 contribution is less than $600 spend, state that gap plainly and check whether repeat sales or lower acquisition cost can change the economics before scaling.</p>''',
'cash-flow-forecast-template-example':'''<h2>Use a spreadsheet layout that survives updates</h2><p>Put weeks 1–13 across the columns and payment categories down the rows. Keep “expected” and “confirmed” customer receipts separate. A confirmed invoice is still not collected cash; use the expected bank date, then replace it with the actual date when paid. List supplier invoices, payroll, rent, taxes and loan payments individually when timing matters. A single “other” row can conceal the week that causes a shortfall.</p><p>Freeze the first row with week-ending dates, and use one formula pattern across all 13 columns: closing balance equals opening balance plus receipts minus payments. Check that week 2 opening matches week 1 closing. A negative projected week calls for a concrete action and date, not a negative sign left in a cell. Keep a copy of each week’s forecast so changes in expected receipts can be traced.</p><h2>Compare actuals with the previous forecast</h2><p>Suppose week 1 ended at $5,900 rather than $6,300. The $400 gap could be an unpaid customer receipt, an unexpected $400 bill or two smaller differences. Reconcile each row to bank activity and update the future timing. If an overdue invoice is rescheduled to week 3, avoid adding it as a new sale there; it is the same receipt moving dates. The <a href="https://www.irs.gov/businesses/small-businesses-self-employed/how-should-i-record-my-business-transactions">IRS recordkeeping guidance</a> describes maintaining transaction evidence separately from a planning forecast.</p>''',
'weekly-digital-planner-small-business':'''<h2>Choose the digital format by the work it must support</h2><p>A calendar-style planner is useful for timed commitments and reminders. A task board is better for work moving through stages. An offline planner may suit a person who needs local access without a live connection. Before choosing, check how a product stores data, exports it, works on your device and handles updates. Do not assume a digital planner syncs across devices or integrates with your order system unless its product page says so.</p><p>For this owner, a week view needs at least a date, time, task owner, status and source link. A supplier comparison can live in its own record while a Tuesday block points to it. Make “ship 20 orders” measurable: two packing sessions, a Thursday exception buffer and a Friday check on tracking numbers. The weekly goal is done only when shipment evidence exists, not when a box in the planner is ticked.</p><h2>Protect room for interruptions</h2><p>Suppose each of 20 orders takes seven minutes to pick and pack. That is 140 minutes of direct work before labels, messages and exceptions. The two 90-minute blocks allow 180 minutes, leaving 40 minutes of buffer. If actual time averages ten minutes, the work takes 200 minutes and the plan is 20 minutes short. Update the next week’s estimate using actual timing, and keep the Thursday buffer available until shipment is confirmed.</p>''',
'small-business-budget-example':'''<h2>Make the variance actionable</h2><p>At 90 orders and $80 per order, actual sales of $7,200 are internally consistent. The $100 decrease in total variable costs compared with budget looks favorable at first, but cost per order rose from $28 to $30. The lower total cost is largely a result of fewer orders. Separate a volume effect from a unit-cost effect before praising the cost control.</p><p>The owner can calculate the expected variable cost at actual volume as 90 × $28 = $2,520. Actual variable cost of $2,700 exceeds that by $180. That is the unit-cost variance to investigate. Check supplier invoices, shipping zones and payment fees. The fixed-cost $100 excess may be an unplanned repair or an ongoing price change; classify it before carrying it into next month.</p><h2>Set a budget review rhythm</h2><p>At month-end, lock the actual period and retain the original budget. On the first working day of the next month, compare order count, average price, variable cost per order and fixed cost by category. Write one action with an owner and due date for each material difference. A budget is a forecast of choices, so a changed assumption should appear as a new dated version rather than silently overwriting the old plan. Use the bank and accounting records as the source of actuals.</p>'''
}

for item in articles:
    item['body']+=extras[item['slug']]+DEEP_PLANS[item['slug']]+IMPLEMENTATION_NOTES[item['slug']]
    steps=re.findall(r'<h3>(Step [1-5] — [^<]+)</h3>',item['body'])
    assert 4<=len(steps)<=5,(item['slug'],steps)
    for number,label in enumerate(steps,1):
        item['body']=item['body'].replace(f'<h3>{label}</h3>',f'<h3 id="step-{number}">{label}</h3>',1)
    toc='<nav class="toc" aria-label="Complete plan steps"><strong>Jump to the full plan</strong><ol>'+''.join(
        f'<li><a href="#step-{i}">{html.escape(label)}</a></li>' for i,label in enumerate(steps,1)
    )+'</ol></nav>'
    item['body']=item['body'].replace('</div>', '</div>'+toc,1)

image_alts={
    'retail-store-business-plan-example':'Boutique owner assembling clothing stock, size plan, shipping supplies and a sales forecast under Retail Business Plan',
    'freelance-business-plan-example':'Freelance designer reviewing client work and a calendar under Freelance Business Plan',
    'equipment-rental-business-plan-example':'Event lighting rental team inspecting equipment and a booking handoff under Equipment Rental Plan',
    'saas-business-plan-template-example':'Founder reviewing subscriber growth and cash runway charts under SaaS Business Plan',
    'one-page-marketing-plan-example':'Boutique marketing plan with audience, offer, channels, budget and calendar under One-Page Marketing Plan',
    'cash-flow-forecast-template-example':'Shop owner reviewing a 13-week cash flow chart and invoices under 13-Week Cash Flow',
    'weekly-digital-planner-small-business':'Tablet weekly calendar beside small-business parcels and task notes under Weekly Digital Plan',
    'small-business-budget-example':'Owner comparing planned and actual costs on two budget sheets under Small Business Budget',
}

for item in articles:
    slug=item['slug']; title=item['title']; esc=html.escape
    url=f'{SITE}/journal/{slug}/'; image=f'/images/journal/{slug}-v2.jpg'
    desc=item['subtitle']+' Includes a worked numerical example, assumptions and practical decisions.'
    alt=image_alts[slug]
    assert (ROOT/image.lstrip('/')).is_file(),image
    schema={'@context':'https://schema.org','@type':'BlogPosting','@id':url+'#article','headline':title,'description':desc,'image':SITE+image,'mainEntityOfPage':url,'author':{'@type':'Organization','name':'NexalyPlanner','url':SITE+'/about/'},'publisher':{'@type':'Organization','name':'NexalyPlanner','url':SITE+'/'},'datePublished':DATE,'dateModified':DATE,'inLanguage':'en-US'}
    head=f'''<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{url}"><meta property="og:image" content="{SITE+image}"><meta name="twitter:image" content="{SITE+image}"><meta property="og:image:alt" content="{esc(alt)}"><meta property="article:published_time" content="{DATE}"><meta property="article:modified_time" content="{DATE}"><meta property="og:type" content="article">{styles}<link rel="stylesheet" href="/assets/css/style.css?v=4"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False).replace('<','\\u003c')}</script></head><body>'''
    hero=f'''<header class="article-hero"><div class="brand">NEXALYPLANNER JOURNAL</div><h1>{esc(title)}</h1><p class="metadata">NexalyPlanner Journal · {esc(item['tag'])} · Published September 28, 2026</p></header>'''
    article=f'''<main><p class="toplink"><a href="/journal/">Back to the NexalyPlanner Journal</a></p><article class="reading"><figure class="article-feature"><img src="{image}" width="1200" height="800" alt="{esc(alt)}" fetchpriority="high" decoding="async"><figcaption>Topic-specific editorial illustration; the worked numbers in this plan are hypothetical.</figcaption></figure><p class="article-byline">By NexalyPlanner · Published September 28, 2026 · Expanded September 28, 2026</p>{item['body']}<aside class="related-guides"><h2>Continue planning</h2><ul><li><a href="{item['related']}">Explore the relevant Nexaly planner</a></li><li><a href="/journal/">Read more planning guides</a></li></ul></aside></article></main>'''
    out=ROOT/'journal'/slug/'index.html';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(head+nav+hero+article+footer)
print(f'Authored {len(articles)} expanded journals with editorial photo covers')
