#!/usr/bin/env python3
"""Check the owner-requested core freeze while allowing editorial content edits."""
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / 'docs/core-lock.json'


def digest(value):
    return hashlib.sha256(value.encode() if isinstance(value, str) else value).hexdigest()


def snapshot():
    files = {}
    for p in sorted((ROOT / 'demos').glob('*/index.html')):
        files[str(p.relative_to(ROOT))] = digest(p.read_bytes())
    for name in ['assets/css/style.css', 'bundles/index.html', 'assets/img/logo-mark.png', 'assets/img/logo-light.png']:
        p = ROOT / name
        if p.exists():
            files[name] = digest(p.read_bytes())
    js = (ROOT / 'assets/js/main.js').read_text()
    # Product/post JSON arrays are editorial data regenerated by seo-build.py.
    tail = js.index('var heartSvg =')
    files['assets/js/main.js:behavior'] = digest(js[:js.index('var products =')] + js[tail:])
    products = {}
    for p in sorted((ROOT / 'planners').glob('*/index.html')):
        text = p.read_text()
        links = sorted(set(re.findall(r'https://buy\.polar\.sh/[A-Za-z0-9_]+', text)))
        if not links:
            continue
        chunks = []
        for pattern in [r'<header\b.*?</header>', r'<footer\b.*?</footer>', r'<style\b.*?</style>']:
            chunks.extend(re.findall(pattern, text, re.S))
        for match in re.finditer(r'<script\b([^>]*)>(.*?)</script>', text, re.S):
            attrs, body = match.groups()
            if 'application/ld+json' in attrs:
                continue
            # Allow generated JS cache-busting revisions, not changes in script behavior.
            attrs = re.sub(r'(src=["\'][^"\'?]+)\?[^"\']*', r'\1', attrs)
            chunks.append(attrs + body)
        prices = []
        for raw in re.findall(r'<script\b[^>]*application/ld\+json[^>]*>(.*?)</script>', text, re.S):
            data = json.loads(raw)
            if data.get('@type') == 'Product':
                offer = data.get('offers', {})
                prices.append([offer.get('price'), offer.get('priceCurrency')])
        products[str(p.relative_to(ROOT))] = {'checkout': links, 'prices': prices, 'core': digest('\n'.join(chunks))}
    return {'files': files, 'products': products}


if __name__ == '__main__':
    current = snapshot()
    if '--write' in sys.argv:
        BASELINE.write_text(json.dumps(current, indent=2, sort_keys=True) + '\n')
        print('Wrote core baseline; review changes only within owner-authorized scope.')
    else:
        expected = json.loads(BASELINE.read_text())
        changed = []
        for group in ['files', 'products']:
            for name in sorted(set(expected[group]) | set(current[group])):
                if expected[group].get(name) != current[group].get(name):
                    changed.append(name)
        if changed:
            print('Core freeze requires explicit review; changed: ' + ', '.join(changed))
            sys.exit(1)
        print(f'PASS core freeze: {len(current["products"])} products; {len(current["files"])} protected files/sections. Provider account state is not validated here.')
