"""Detailed, worked operating plans for the September 2026 journal batch."""

DEEP_PLANS = {
    'retail-store-business-plan-example': '''
<h2>A complete boutique plan, from research to the day-90 review</h2>
<h3>Step 1 — Define the buyer and validate the range before ordering</h3>
<p>Willow Thread is a fictional online boutique serving local buyers who want coordinated everyday outfits and weekend pickup. The owner writes down a specific promise: 12 easy-to-combine styles, clear size information, and a $36 average item price. Before buying 120 units, she speaks with 20 potential buyers, shows sample photographs and size charts, and asks what they bought recently, what fit or delivery problem they encountered, and what they would actually pay. An expression of interest is not an order. She logs recurring objections, not just compliments.</p>
<p>She then checks five comparable shops: price range, shipping or pickup terms, visible size coverage, return terms and how products are shown. The comparison is a planning input, not proof that Willow Thread will win customers. If interviews reveal that the target buyers need sizes the supplier cannot provide, she revises the range before paying for inventory.</p>
<h3>Step 2 — Write the assortment, supply and fulfillment rules</h3>
<p>Allocate the 120 initial units by style and size rather than ordering ten units of every style blindly. One sample allocation is 40 units of proven basics, 50 units across five complementary styles and 30 units across six test styles. The owner records each SKU, landed unit cost, supplier minimum, lead time, size and opening quantity. The $18 landed cost must include the applicable purchase and freight components; she confirms it from the actual supplier quote.</p>
<p>For each order, the workflow is payment confirmation → stock reservation → picking and size check → packing → dispatch or pickup confirmation → return or exchange handling. An order awaiting payment does not reduce the same stock field as a paid reservation. A damaged return does not go directly back into sellable stock. The <a href="/planners/inventory-procurement-planner/">Inventory &amp; Procurement Planner</a> is a relevant tool for the purchase and stock handoff; the product page describes its actual features.</p>
<h3>Step 3 — Establish a cash ceiling and unit economics</h3>
<p>Opening cash is $4,800. Initial inventory uses $2,160; the first month’s listed operating costs use $505. Add a $300 photography/setup allowance and protect a $1,000 contingency. That leaves $835 available for further commitments before customer receipts: $4,800 − $2,160 − $505 − $300 − $1,000. This is a decision ceiling, not profit. At $36 price and $18 unit cost, each retained full-price sale contributes $18 before packaging, payment fees, returns and fixed spending. If the $505 is treated as monthly fixed spending for a simple threshold, at least 29 retained sales are needed to cover it ($505 ÷ $18, rounded up); this excludes the other costs just named.</p>
<h3>Step 4 — Execute a dated 90-day launch</h3>
<div class="table-wrap"><table><caption>Willow Thread’s illustrative workback plan</caption><thead><tr><th>When</th><th>Owner action</th><th>Evidence or gate</th></tr></thead><tbody><tr><td>Days 1–14</td><td>Interview 20 buyers; compare five stores; order and inspect samples</td><td>Document fit, price and return objections before a bulk order</td></tr><tr><td>Days 15–30</td><td>Confirm supplier terms, receive 120 units, photograph 12 styles, test checkout and pickup</td><td>SKU count reconciles; a test order can be fulfilled end to end</td></tr><tr><td>Days 31–60</td><td>Launch; record sales and returns by size each Friday</td><td>Use actual margin and lead time to approve or pause replenishment</td></tr><tr><td>Days 61–90</td><td>Reorder proven sizes, retire weak test styles, compare the forecast with cash and stock</td><td>Document keep, change or stop decisions for the next quarter</td></tr></tbody></table></div>
<p>The existing illustration sells 60 units in month 1. A scenario of 50 units in month 2 and 60 in month 3 totals 170. With only 120 units initially, at least 50 replacement units must arrive before those later sales; at $18 each that is another $900 cash outflow. In a stripped-down cash illustration, $4,800 opening cash + $6,120 receipts − $2,160 initial stock − $900 replenishment − $1,515 three months of stated operating costs − $300 setup = $6,045 before fees, refunds, taxes and owner withdrawals. The business still needs size-level timing: a total of 170 units available over 90 days does not prevent a popular size from selling out in week 4.</p>
<h3>Step 5 — Monitor downside and set the next decision</h3>
<p>If month-1 sales are only 35 units, receipts at the assumed $36 price are $1,260 rather than $2,160, a $900 shortfall. Do not automatically buy more stock to chase the original forecast. Review product-page visits, size questions, abandoned orders, returns and the five comparable offers. At day 90, replace assumptions with actual selling price, cost, units sold, returns, available cash and unsold stock. Decide which sizes to reorder, which styles to discontinue and how much cash can safely fund the next batch.</p>
''',
    'freelance-business-plan-example': '''
<h2>The complete freelancer plan: first client through repeatable delivery</h2>
<h3>Step 1 — Identify a specific client and a paid problem</h3>
<p>The fictional designer serves small service businesses whose landing page is unclear or hard to update. She interviews five prospects about recent launches, lost inquiries, decision makers, budgets and approval delays. She reviews three competing offers and writes one outcome in plain language: a clear landing-page design ready for implementation, with an agreed number of pages and revision rounds. A client’s interest in a free call is not demand for the $1,250 package; the first paid pilot tests that assumption.</p>
<h3>Step 2 — Define the offer, scope and acceptance</h3>
<p>The package includes a 45-minute discovery session, one page structure, a visual design, one handoff file and two consolidated revision rounds. The scope lists the client’s required copy, brand assets and approval contact, plus what is excluded: development, ongoing advertising and extra pages. A written proposal states price, milestones, payment timing, delivery dates, change-request pricing and what counts as final acceptance. Those terms should be checked against the actual contract; the planner merely tracks them.</p>
<h3>Step 3 — Price against capacity, not an optimistic calendar</h3>
<p>At $1,250 for 20 planned client hours, the package yields $62.50 per planned client hour before expenses. Three packages need 60 hours, leaving 20 of 80 working hours for prospecting, admin and buffer. Allocate those 20 explicitly: eight for inquiries/proposals, four for finance/admin, four for learning and four for delay. If each project instead needs 26 hours, three need 78 and only two hours remain. At that point, pause new bookings, narrow scope or raise price rather than silently sacrificing delivery.</p>
<h3>Step 4 — Build a measurable sales process</h3>
<div class="table-wrap"><table><caption>Illustrative freelancer acquisition and delivery workback</caption><thead><tr><th>Stage</th><th>Monthly assumption</th><th>Next action if missed</th></tr></thead><tbody><tr><td>Qualified inquiries</td><td>12</td><td>Review referral requests and the clarity of the offer</td></tr><tr><td>Written proposals</td><td>8</td><td>Review qualification and response time</td></tr><tr><td>Accepted projects</td><td>3, or 37.5% of proposals</td><td>Review objections, scope and price separately</td></tr><tr><td>Delivered and accepted</td><td>3 with about 20 hours each</td><td>Inspect actual hours and blocked approvals</td></tr></tbody></table></div>
<p>Each inquiry has a source, client need, next action and follow-up date. Each accepted project gets a kickoff checklist, client-asset deadline, design block, review date and invoice milestone. She does not count an unsigned proposal as booked revenue or an invoice as collected cash.</p>
<h3>Step 5 — Plan cash and the first 90 days</h3>
<p>Three projects invoice $3,750. The illustrative $600 of software and contractor costs leaves $3,150 before other overhead, taxes and owner compensation. If each client pays half at booking and half at acceptance, only $1,875 may arrive at booking; collectability and delivery dates determine the other half. For a sample allocation after all $3,750 is actually collected, she earmarks $600 for the stated direct costs, $900 for a tax/contingency reserve chosen for this example and $1,000 for owner withdrawal, leaving $1,250. The $900 is not a recommended tax percentage.</p>
<p>Days 1–30: interview five prospects, document the package and complete one paid pilot. Days 31–60: refine the scope from actual hours, request permitted referrals and aim for 12 qualified inquiries. Days 61–90: compare inquiry-to-proposal, proposal-to-win, estimated-to-actual hours, acceptance delays and cash collected. If one $1,250 final payment is late, revise the cash calendar before committing the next contractor expense. Retain a dated version of the plan and change one assumption at a time.</p>
''',
    'equipment-rental-business-plan-example': '''
<h2>The equipment rental plan, from asset choice to expansion</h2>
<h3>Step 1 — Validate the event and customer</h3>
<p>The fictional rental owner considers one portable lighting kit for small local events. Before buying, she speaks with venue coordinators and event organizers about event size, typical notice period, transport, setup and cancellation concerns. She compares three local rental offers on included equipment, delivery radius, setup, deposits and return time. She confirms that the kit meets the intended use and gets suitable insurance and contract advice for the actual operation. This example is about event equipment, not residential rentals.</p>
<h3>Step 2 — Specify the kit and its usable calendar</h3>
<p>Create an asset record with purchase cost ($2,400 assumed), components, serial numbers, photos, test results, cleaning steps and maintenance history. Only 20 dates are genuinely available in the illustrative month after closures and turnaround. The kit may not be promised to two customers for the same date, and a late return can block the next booking. A date becomes unavailable when a confirmed booking, inspection or repair occupies it; a mere quote has a separate expiry and status.</p>
<h3>Step 3 — Quote the full job and control the handoff</h3>
<p>At $90 per booking, clarify what is included: pickup or a defined local delivery, setup, duration, power requirements and return condition. An inquiry moves through availability check → written quote → accepted terms and payment condition → pre-rental inspection → dispatch/pickup proof → return inspection → deposit reconciliation → cleaning and ready status. Photograph condition before and after. A refundable deposit is a liability until terms for release or permitted deductions are resolved; it is not ordinary rental revenue.</p>
<h3>Step 4 — Model utilization and downside cash</h3>
<div class="table-wrap"><table><caption>Illustrative month at ten bookings</caption><thead><tr><th>Line</th><th>Calculation</th><th>USD</th></tr></thead><tbody><tr><td>Receipts</td><td>10 × $90</td><td>$900</td></tr><tr><td>Routine variable cost</td><td>10 × $18</td><td>−$180</td></tr><tr><td>Fixed cost allocation</td><td>Storage, insurance and other assumed costs</td><td>−$400</td></tr><tr><td>Illustrative remainder</td><td>$900 − $180 − $400</td><td>$320</td></tr><tr><td>Chosen replacement reserve</td><td>Cash set aside for this example</td><td>−$120</td></tr><tr><td>Cash available before tax/owner pay</td><td>$320 − $120</td><td>$200</td></tr></tbody></table></div>
<p>At $72 contribution per booking after the stated $18 variable cost, six bookings cover the $400 fixed allocation when rounded up; this excludes the $120 reserve and purchase cost. Recovering a $2,400 purchase from $200 a month would take 12 identical months under these simplified assumptions. A $360 repair in month 2 or seasonal idle periods would lengthen it. Do not treat the deposit as financing the kit.</p>
<h3>Step 5 — Launch small, inspect weekly, and expand by evidence</h3>
<p>Days 1–30: confirm demand, terms, insurance, kit contents and a tested handoff checklist. Days 31–60: accept a limited number of bookings and measure quote response time, completed bookings, turnaround hours and damage. Days 61–90: compare 20 genuinely available dates with booked dates, cash contribution by job and declined requests. If there are 15 requests but only eight bookings, review price, availability and quote speed. If 10 bookings produce three repairs, improve handling before buying another kit. Approve a second kit only when repeat demand, maintenance capacity and the cash plan support it.</p>
''',
    'saas-business-plan-template-example': '''
<h2>The SaaS plan from customer problem to a tested runway</h2>
<h3>Step 1 — Choose one workflow and prove the problem</h3>
<p>The fictional software team interviews a narrow group of potential customers about a recurring workflow, its current tools, monthly cost of the problem and who can authorize payment. They document at least five recent examples rather than asking whether a speculative feature sounds useful. They compare alternatives, including manual work and existing software. A waiting-list signup is not a paying account, so the first milestone is a paid, usable workflow with support and cancellation paths.</p>
<h3>Step 2 — Define the offer and service boundary</h3>
<p>The initial $30 monthly plan states the user, included workflow, limits, support channel, data handling, billing date and cancellation terms. It distinguishes an active paying account from trial users and failed payments. The team maintains a source of truth for subscriptions, invoices, refunds and access. It measures successful onboarding and time to first useful result. Privacy, security and legal commitments must match the actual product and applicable requirements, not a promise invented for the business plan.</p>
<h3>Step 3 — Build an acquisition and retention model</h3>
<p>The illustration starts with 100 paying accounts, adds 20 at an assumed $40 acquisition spend each and loses five at month-end. Ending accounts are 115 and marketing spend is $800. Starting-account logo churn is 5/100 = 5% for this one month. Track where the 20 came from, which cohort they joined, how many activated and why five left. Do not extend one observed month into a lifetime value claim. At $30 price and an illustrative $4 service cost per account, $26 is a narrow monthly contribution before support, payment fees and overhead.</p>
<h3>Step 4 — Link the operating plan to monthly cash</h3>
<div class="table-wrap"><table><caption>Illustrative three-month cash path, with all customers billed as described</caption><thead><tr><th>Month</th><th>Start + adds − losses = end</th><th>Assumed receipts</th><th>Outflows</th><th>Net cash</th></tr></thead><tbody><tr><td>1</td><td>100 + 20 − 5 = 115</td><td>$3,300</td><td>$460 service + $800 acquisition + $3,000 other = $4,260</td><td>−$960</td></tr><tr><td>2</td><td>115 + 20 − 6 = 129</td><td>$3,750</td><td>$516 + $800 + $3,000 = $4,316</td><td>−$566</td></tr><tr><td>3</td><td>129 + 20 − 6 = 143</td><td>$4,170</td><td>$572 + $800 + $3,000 = $4,372</td><td>−$202</td></tr></tbody></table></div>
<p>The illustrative receipts count starting accounts at $30 and new accounts at a half-month $15. Cancellations occur at month-end. With $12,000 starting cash, the simplified closing cash after these three net movements is $10,272. Real billing cycles, annual prepayments, refunds, taxes and unpaid invoices can change cash substantially. The month-1 snapshot runway of 12.5 months is not a three-month forecast; the dated table is more useful.</p>
<h3>Step 5 — Set decision gates and a downside case</h3>
<p>In the first 30 days, confirm activation and support load for the initial cohort. By day 60, compare acquisition cost and cancellations by cohort, not just aggregate signups. By day 90, reconcile billings to bank receipts and update the 12-month cash schedule. If receipts are $2,500 while the month-1 $4,260 outflows persist, cash burn is $1,760 and $12,000 divided by it is about 6.8 months before the other changes. Pause additional acquisition spend if the service cannot onboard or retain customers at a supportable cost; document the next experiment and its stop date.</p>
''',
    'one-page-marketing-plan-example': '''
<h2>The full work behind the one-page marketing plan</h2>
<h3>Step 1 — Research a buyer and write a specific offer</h3>
<p>The boutique asks ten recent or prospective buyers what they bought for work, what prevented a prior purchase, which sizes and pickup options matter, and how they discover new clothing. It compares three direct alternatives on price, styling guidance and delivery terms. The one-page document names local workwear buyers as its audience and a four-piece capsule under $75 per item as its offer. The interviews may disprove those assumptions; a plan records the evidence and revision date rather than presenting a fictional persona as fact.</p>
<h3>Step 2 — Set one business goal and the economics before content</h3>
<p>The 30-day test aims for eight retained paid orders, with a $600 maximum marketing commitment. The illustrative contribution after product and fulfillment cost is $38 per retained order. Eight orders contribute $304, leaving a $296 shortfall against the $600 marketing spend. To cover that spend on immediate contribution alone, the ceiling would require 16 retained orders because 15 × $38 = $570 and 16 × $38 = $608. At the assumed 10% visit-to-order rate, that would take around 160 comparable qualified visits rather than 80. These are planning sensitivities, not a prediction.</p>
<h3>Step 3 — Choose channels and define attribution</h3>
<p>Use email to existing subscribers and short product demonstrations as the two initial channels. Allocate $360 to creative production and $240 to distribution, with an owner who must approve any spend before the ceiling is exceeded. Each campaign link uses a consistent source label, and the order record retains its original source and purchase date. A buyer may see several touches; this small plan uses the last trackable campaign link as a working rule and labels unattributed orders separately. Do not award every order to both channels.</p>
<h3>Step 4 — Build a 30-day calendar and approval path</h3>
<div class="table-wrap"><table><caption>Illustrative four-week campaign schedule</caption><thead><tr><th>Week</th><th>Work and owner</th><th>Release check</th></tr></thead><tbody><tr><td>1</td><td>Owner checks stock, fit notes, prices and offer terms; photographer creates images</td><td>Product pages, size guide, checkout and pickup tested</td></tr><tr><td>2</td><td>Two emails and three short demonstrations; record spend and source labels</td><td>Every link works and stock shown is available</td></tr><tr><td>3</td><td>Repeat the useful format; answer fit questions; inspect refunds and cart drop-off</td><td>No unsupported claims or misleading offer deadline</td></tr><tr><td>4</td><td>Publish final planned assets, close the test and export orders and spend</td><td>Day-31 decision uses retained orders and contribution</td></tr></tbody></table></div>
<p>For each email, the workback is product facts → draft → offer and link review → send → reply handling. For each demonstration, the workback is item selection → shoot → captions → stock check → publish → questions. Set deadlines and backups; an attractive calendar without production capacity will slip.</p>
<h3>Step 5 — Measure, diagnose and decide</h3>
<p>Review qualified visits, add-to-cart events, paid orders, cancellations, refunds, contribution and spend each week. If 80 visits produce eight paid orders but two cancel, retained orders are six and spend is $100 per retained order. On day 31, separate whether the issue is low relevant traffic, low conversion, low contribution or returns. Change one variable for the next test, such as a clearer size guide, and state the metric and stop date. The one-page sheet is the decision summary; keep underlying campaign and financial records available for audit.</p>
''',
    'cash-flow-forecast-template-example': '''
<h2>Build the 13-week forecast from a bank balance to a weekly decision</h2>
<h3>Step 1 — Set the starting cash and source records</h3>
<p>On the chosen Monday, reconcile the $5,000 opening amount to the business bank account. List customer invoices and expected collection dates, recurring bills, supplier payment terms, payroll, tax payments and known one-off purchases. Record an owner and source for each line. A sales target, unsigned quote or issued invoice is not cash in the bank. If the business has restricted funds, identify them separately rather than treating all account balances as freely spendable.</p>
<h3>Step 2 — Lay out every week and calculate closing cash</h3>
<p>Create 13 columns with week-ending dates and rows for opening cash, confirmed receipts, uncertain receipts, supplier payments, payroll, occupancy, tax, debt and other commitments. The compact table below rolls categories into total receipts and payments for readability. Week 1 closes at $6,300. Week 2 opens at exactly $6,300, and the same carry-forward rule applies across the horizon.</p>
<div class="table-wrap"><table><caption>Illustrative complete 13-week cash forecast, USD</caption><thead><tr><th>Week</th><th>Opening</th><th>Receipts</th><th>Payments</th><th>Closing</th></tr></thead><tbody><tr><td>1</td><td>5,000</td><td>2,800</td><td>1,500</td><td>6,300</td></tr><tr><td>2</td><td>6,300</td><td>1,700</td><td>3,200</td><td>4,800</td></tr><tr><td>3</td><td>4,800</td><td>2,100</td><td>2,700</td><td>4,200</td></tr><tr><td>4</td><td>4,200</td><td>2,000</td><td>2,000</td><td>4,200</td></tr><tr><td>5</td><td>4,200</td><td>2,600</td><td>2,100</td><td>4,700</td></tr><tr><td>6</td><td>4,700</td><td>1,800</td><td>2,500</td><td>4,000</td></tr><tr><td>7</td><td>4,000</td><td>2,200</td><td>2,300</td><td>3,900</td></tr><tr><td>8</td><td>3,900</td><td>3,000</td><td>1,900</td><td>5,000</td></tr><tr><td>9</td><td>5,000</td><td>2,400</td><td>2,600</td><td>4,800</td></tr><tr><td>10</td><td>4,800</td><td>1,600</td><td>2,700</td><td>3,700</td></tr><tr><td>11</td><td>3,700</td><td>2,800</td><td>2,100</td><td>4,400</td></tr><tr><td>12</td><td>4,400</td><td>2,300</td><td>3,000</td><td>3,700</td></tr><tr><td>13</td><td>3,700</td><td>2,600</td><td>2,200</td><td>4,100</td></tr></tbody></table></div>
<p>Every closing figure equals opening + receipts − payments; the $4,100 at week 13 is a forecast, not an ending bank statement. Weeks 10 and 12 are the lowest baseline closing weeks at $3,700. A reserve threshold should reflect actual upcoming commitments, not an arbitrary universal percentage. The detailed rows behind the totals tell the owner what can be changed.</p>
<h3>Step 3 — Add a downside case and an action owner</h3>
<p>Move a $1,200 receipt from week 2 to week 5, without duplicating it. Week 2 closes at $3,600, week 3 at $3,000 and week 4 at $3,000; week 5 returns to the baseline $4,700 once that receipt arrives. If the owner sets a $3,500 internal cash threshold for this example, weeks 3 and 4 breach it. The action is specific: confirm the invoice collection date, review a discretionary purchase that can genuinely move, and agree any supplier change rather than assuming a bill can simply be delayed. Record the responsible person and decision date.</p>
<h3>Step 4 — Roll the forecast each Friday</h3>
<p>Replace the past week’s projected entries with actual bank movements, explain material differences and add a new week 13. Keep the prior forecast snapshot; otherwise the accuracy of collection and payment assumptions disappears. Check opening-to-closing carryover, duplicate receipts, tax dates and payments made on weekends. The <a href="/planners/cashflow-13-os/">CashFlow 13 planner</a> can support the rolling view, while the bank and bookkeeping records remain the financial source of truth.</p>
''',
    'weekly-digital-planner-small-business': '''
<h2>Build a complete working week, from monthly goal to Friday handoff</h2>
<h3>Step 1 — Collect commitments before adding tasks</h3>
<p>On Friday afternoon, the fictional shop owner collects next week’s 20 paid open orders, promised shipment dates, one supplier decision, a launch email deadline and existing appointments. She checks the order and inventory records before putting anything in the planner. A monthly goal such as “launch the new range” becomes this week’s three verifiable outcomes: ship 20 orders, confirm a supplier by Wednesday and approve the launch email by Friday. A vague activity like “work on marketing” is not an outcome.</p>
<h3>Step 2 — Estimate effort and reserve capacity</h3>
<p>At seven minutes of pick-and-pack time per order, 20 orders require 140 minutes of direct work. Two 90-minute sessions provide 180 minutes, leaving a 40-minute direct-work buffer before customer messages and exceptions. Add a one-hour supplier comparison and a two-hour email block: six focused hours total. Four hours of customer support and two hours of bookkeeping are already committed. The owner leaves Thursday as an exception buffer, rather than filling every available hour with new projects.</p>
<div class="table-wrap"><table><caption>Illustrative week with an explicit handoff</caption><thead><tr><th>Day</th><th>Work block</th><th>Input</th><th>Done when</th></tr></thead><tbody><tr><td>Monday</td><td>09:00–10:30 pack batch A</td><td>Ten paid orders and pick list</td><td>Ten tracking records and stock deductions checked</td></tr><tr><td>Tuesday</td><td>11:00–12:00 compare suppliers</td><td>Three like-for-like quotes</td><td>Landed cost and lead time recorded; decision owner named</td></tr><tr><td>Wednesday</td><td>09:00–10:30 pack batch B</td><td>Ten remaining orders</td><td>Tracking or a documented exception for each</td></tr><tr><td>Thursday</td><td>Exception buffer</td><td>Missing addresses or failed labels</td><td>Thursday shipping promise met or customer updated</td></tr><tr><td>Friday</td><td>14:00–16:00 email; 16:00 review</td><td>Approved product facts and stock</td><td>Links checked, email scheduled, three outcomes reviewed</td></tr></tbody></table></div>
<h3>Step 3 — Keep task status and evidence together</h3>
<p>Each planner entry needs an owner, date, next action, status and link to the source record. The order system holds addresses and payments; the planner holds the block and exception follow-up. The supplier comparison keeps unit price, freight, minimum order and delivery date. If a quote is $15 per unit plus $80 freight for 40 units, landed cost is $17 per unit; the owner compares that with the other two quotes under the same quantity and terms before approving one.</p>
<h3>Step 4 — Run the week and replan when reality changes</h3>
<p>Each morning, confirm fixed appointments, choose the next action for each of the three outcomes and check deadlines. If one 90-minute packing block produces only eight shipments, log the cause: missing addresses, stock mismatch or an underestimated pick time. Move the two exceptions into Thursday’s buffer and notify customers where a promise changes. Do not mark an order complete when only a label was printed.</p>
<h3>Step 5 — Review and hand the next week forward</h3>
<p>On Friday, compare 20 promised shipments with tracking evidence, supplier decision with the accepted quote, and the email with an approved draft and working links. If 16 shipped and four addresses were missing, next week’s first action is address collection, not a generic repeat of “ship four.” Update time per order: at ten minutes, 20 orders require 200 minutes, so the next schedule needs another block or a smaller commitment. Archive the week, retain blocked items with owners and dates, and choose next week’s outcomes from the monthly milestone. The <a href="/planners/small-business-planner-2026-2028/">Small Business Planner</a> is relevant for this kind of dated planning; verify its exact format on the product page.</p>
''',
    'small-business-budget-example': '''
<h2>Build the budget from a sales assumption to a controlled review</h2>
<h3>Step 1 — Set the period and activity driver</h3>
<p>The fictional shop budgets one calendar month, with 100 paid orders at an $80 average price. That is $8,000 of planned sales before refunds. The owner records the source of the 100-order assumption, such as recent order history and available stock, rather than inserting a growth target without capacity. If product and service lines have different margins, budget them separately instead of treating every order as identical.</p>
<h3>Step 2 — Separate unit costs, fixed bills and owner cash needs</h3>
<p>Variable product, shipping and payment costs are assumed to average $28 per order: 100 × $28 = $2,800. Fixed costs are $1,200 rent, $600 software/utilities, $600 marketing and $400 insurance, totaling $2,800. Planned operating remainder is $8,000 − $2,800 − $2,800 = $2,400 before tax, financing and owner pay. The owner proposes a $1,600 withdrawal and retains an $800 illustrative cushion. Because an owner draw may not be an income-statement expense, the formal accounting treatment must be determined separately.</p>
<h3>Step 3 — Calculate a threshold and check timing</h3>
<p>Each budgeted order contributes $80 − $28 = $52 before fixed costs. Covering the $2,800 fixed budget takes 54 orders when rounded up ($2,800 ÷ $52 = 53.85). If the owner also wants a $1,600 cash withdrawal, a simplified activity threshold becomes 85 orders: ($2,800 + $1,600) ÷ $52 = 84.62. Neither threshold includes tax, debt service, refunds or one-time purchases. Payment dates matter: if $800 of the $7,200 actual sales is collected next month, current-month cash receipts are only $6,400 under the illustration.</p>
<h3>Step 4 — Assign spending controls</h3>
<div class="table-wrap"><table><caption>Illustrative monthly controls</caption><thead><tr><th>Category</th><th>Budget owner and action</th><th>Trigger to review</th></tr></thead><tbody><tr><td>Variable cost</td><td>Owner checks supplier price and shipping per order weekly</td><td>Above $28 planned per order</td></tr><tr><td>Marketing</td><td>Owner approves campaigns against the $600 ceiling</td><td>Spend exceeds plan or retained orders disappoint</td></tr><tr><td>Fixed bills</td><td>Bookkeeper checks due dates and actual invoices</td><td>New recurring commitment or $100 variance</td></tr><tr><td>Owner withdrawal</td><td>Owner checks dated cash forecast before transfer</td><td>Available cash falls below upcoming obligations</td></tr></tbody></table></div>
<h3>Step 5 — Close the month, explain variance, and reforecast</h3>
<p>Actual sales of $7,200 reflect 90 orders at $80. Variable costs of $2,700 are $30 per order, not the budgeted $28. At 90 orders, expected variable costs would have been $2,520; the $180 excess is a unit-cost issue. Fixed costs are $2,900, another $100 over plan. The resulting $1,600 operating remainder is $800 below the $2,400 budget. Identify whether fewer orders came from traffic, conversion, stock availability or refunds, and whether the $2 cost increase came from suppliers, shipping or payment fees.</p>
<p>The next-month downside case is 80 orders at $80 with $30 unit costs and $2,900 fixed costs: $6,400 − $2,400 − $2,900 = $1,100 before owner pay and tax. That is $500 short of the proposed $1,600 withdrawal even before timing differences. The decision is to revise the cash withdrawal or underlying sales/cost plan, with a dated owner and evidence source. Retain the original budget and the actuals; do not overwrite the forecast to make it look accurate.</p>
''',
}

IMPLEMENTATION_NOTES = {
    'retail-store-business-plan-example': '''
<h2>Use this weekly control sheet after launch</h2>
<div class="table-wrap"><table><caption>Fields to update every Friday</caption><thead><tr><th>Record</th><th>Source</th><th>Question for the owner</th></tr></thead><tbody><tr><td>Orders and retained units by SKU/size</td><td>Order and return records</td><td>Which size needs replenishment or a clearer fit note?</td></tr><tr><td>Available, reserved and damaged units</td><td>Stock count</td><td>Can the next promotion be fulfilled?</td></tr><tr><td>Actual selling price and landed cost</td><td>Receipts and supplier invoices</td><td>Is the $18 unit contribution still realistic?</td></tr><tr><td>Cash collected and bills due</td><td>Bank and payables</td><td>Can the next purchase order be funded on its due date?</td></tr></tbody></table></div>
<p>Record a stock-count discrepancy as a separate exception, with a person and resolution date. Do not force the inventory number to match the plan. On a return, note whether the customer received a refund, exchange or credit and whether the item is sellable. This prevents a sales report from hiding a stock or cash problem.</p><p>The 90-day decision should state three outputs: a revised assortment, a maximum purchase commitment, and an owner for the next supplier order. If actual demand is concentrated in four sizes, the next order should follow those sizes rather than the original equal split. A plan is complete only when these decisions are made from actual records.</p>
''',
    'freelance-business-plan-example': '''
<h2>Run the client-delivery checklist for every project</h2>
<p>Before kickoff, confirm the decision maker, source files, written scope, invoice contact and review dates. At kickoff, map the page sections and define the one conversion action. During design, log hours against the 20-hour estimate in discovery, production and revisions separately. Send one consolidated review request and record the client’s approval or change request. At acceptance, deliver the agreed handoff files, issue the final invoice and ask for a short retrospective.</p>
<p>A simple status board can use Inquiry → Qualified → Proposal sent → Accepted → In production → Client review → Accepted/paid. Every item needs a next action and date. A client waiting for copy stays in a blocked state rather than consuming a fictional design block. If two clients both delay approval by a week, the owner checks whether the following month’s 60 client hours are still possible before taking another deposit.</p>
<p>The monthly decision sheet records projected versus actual hours per package, cash received versus invoiced, proposal wins and reasons for lost deals. For example, if the three packages take 18, 22 and 26 hours, the average is 22; three at that pace need 66 hours, leaving 14 of the 80-hour month. The next plan should use 22 hours or tighten scope rather than keeping a convenient 20-hour estimate.</p>
''',
    'equipment-rental-business-plan-example': '''
<h2>Keep an asset-level operating record</h2>
<p>For every confirmed booking, capture event date, kit ID, pickup/return windows, customer contact, contract version, paid amount, deposit status and pre/post condition. The return checklist should cover all lights, stands, cables, cases, tests and cleaning. A missing cable can make the next booking impossible even if the calendar says the kit is free. Reserve a maintenance block after a damaged return and notify the next customer if a promise is affected.</p>
<p>Review contribution by completed booking rather than headline price. At the illustrative $90 rate, a local booking with $18 variable cost contributes $72. If a longer delivery adds $35, the same price contributes $37. The owner can add an appropriate delivery charge or limit the service radius, but should state the quote terms before accepting the job.</p>
<p>At month-end, reconcile booking status to invoices and bank receipts, then compare available dates, completed dates and repair closures. A month with 10 completed bookings out of 20 available dates is 50% utilization. If the kit is down for five dates, report both the 15 usable dates and the downtime reason; do not celebrate 10/15 utilization while ignoring preventable repairs.</p>
''',
    'saas-business-plan-template-example': '''
<h2>Maintain the operating evidence behind the forecast</h2>
<p>Use a monthly cohort sheet with signup month, acquisition source, activation, first payment, later payments, cancellation and refund. A trial that never paid belongs in a separate trial funnel. A customer who cancels but retains access until period end needs consistent counting rules; write them down once and apply them every month. Reconcile the subscription system to bank receipts and service invoices before reporting growth to anyone else.</p>
<p>The product workback is problem interviews → narrow usable workflow → billing and cancellation test → onboarding → support queue → cohort review. Assign a named owner and deadline to each. If 20 new customers sign up but ten never complete the first useful action, optimize onboarding before buying another 20 at $40 acquisition cost. If support costs rise above the modeled $4 per account, update both contribution and cash runway.</p>
<p>The 90-day review should produce one decision among continue the narrow offer, change the customer segment, change onboarding or pause acquisition. It should cite activation, retained paying accounts, cash receipts, service cost and support backlog. The model’s $10,272 month-3 cash balance is a scenario output, not proof the product has reached sustainable economics.</p>
''',
    'one-page-marketing-plan-example': '''
<h2>Keep a small campaign brief behind the one-page summary</h2>
<p>For each asset, record the product shown, audience objection addressed, promised benefit, proof available, call to action, destination URL, stock check and approval owner. An email about fit should link to a real size guide; a pickup claim should reflect the actual available area and hours. On launch day, test links on a phone, confirm the offer terms and make sure featured sizes are in stock. The planner can track work; it cannot replace these checks.</p>
<p>Make a simple weekly scorecard with spend, qualified visits, paid orders, retained orders, average contribution and customer questions. In week 2, if spend is $300 but visits are only 20, the channel may be failing to reach the intended audience. If visits are 80 and orders are zero, inspect page clarity, size/price objections and checkout before increasing distribution. If orders come but refunds rise, change product information or the offer, not just ad copy.</p>
<p>At day 31, write the decision in a sentence with a number: “Revise the size guide before a second $240 distribution test because two of eight paid orders were cancelled for fit reasons.” This makes the next campaign a controlled experiment. Keep the original plan and results so the team can tell a revision from a retroactive target change.</p>
''',
    'cash-flow-forecast-template-example': '''
<h2>Audit the formula and collection assumptions</h2>
<p>In a spreadsheet, place the opening amount above each week’s receipts and payments. A sample formula is <code>closing = opening + sum(receipts) - sum(payments)</code>; the next week’s opening cell should point to the previous closing cell. Protect formulas from accidental typing, label USD and week-ending dates, and keep a separate column or comment for confidence and source. The 13-week table’s first four weeks can be checked by hand: $5,000 + $2,800 − $1,500 = $6,300, then $6,300 + $1,700 − $3,200 = $4,800.</p>
<p>When a $1,200 collection is delayed, move the same invoice line from week 2 to week 5 and retain its identifier. Do not create a fresh $1,200 sale in week 5. Compare forecast with bank actuals every Friday, classify each variance as timing, amount or missing item, and revise future weeks. A late receipt is a timing issue; a disputed invoice may also change the amount. Treat those risks differently.</p>
<p>The weekly decision record should name the projected lowest balance, the required minimum for known obligations, the owner of an action and its due date. If a projected payment cannot be met, seek qualified advice and discuss options with the actual counterparty early. A forecast warns of a date-specific gap; it does not authorize withholding a payment.</p>
''',
    'weekly-digital-planner-small-business': '''
<h2>Use a status and exception rule that survives the week</h2>
<p>Keep statuses simple: Next, Scheduled, Waiting, Done and Cancelled. “Waiting” must name the person or condition and a follow-up date. When an order lacks an address, the owner moves it to Waiting, sends the customer a request and reserves Thursday’s buffer for a response. A supplier quote is Done only after an accepted comparison and written confirmation; opening the email is not completion.</p>
<p>During Wednesday’s review, compare estimated with actual time. If ten orders take 100 minutes instead of 70, the remaining ten need about 100 minutes, which is longer than the planned 90-minute block. Move a noncritical task or add a 20-minute buffer before promising Thursday shipment. If the email cannot be approved by Friday, keep the task with the approver and a new realistic date instead of automatically copying it forward.</p>
<p>At the Friday handoff, archive what happened and show the next week’s starting state: unresolved orders, accepted supplier, approved campaign, available stock and fixed appointments. This is where the weekly digital planner becomes an operating tool rather than a decorative schedule.</p>
''',
    'small-business-budget-example': '''
<h2>Use a versioned budget worksheet</h2>
<p>Give the sheet columns for original budget, actual, variance, driver and action. Under sales, record both order count and average price. Under variable cost, record both total and cost per order. Under fixed spending, keep named bills rather than a single “overhead” amount. That lets the owner see that the $100 favorable total variable-cost variance is misleading: there were ten fewer orders, and unit cost actually rose by $2.</p>
<p>Attach a source to each actual: order export for the 90 orders, invoices for the $2,700 variable and $2,900 fixed costs, and bank receipts for cash. If a supplier invoice arrives after month close, record the timing and follow the business’s accounting process; do not silently change a closed actual to make the planning table tidy.</p>
<p>Set the following month’s action with a date. For instance, by day 3 the owner checks the shipping invoices behind the $180 unit-cost difference; by day 5 she reviews lost orders and stockouts; by day 7 she approves a revised order and withdrawal plan that fits the cash forecast. The budget is finished when responsibility and limits are clear, not when the variance table is printed.</p>
''',
}
